/* eslint-disable react/no-unescaped-entities */
export default function Head() {
  return (
    <>
      <title>Mark's Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="author" content="Mark Landeryou marklanderyou@hotmail.com" />

      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
